In [1]:
import pandas as pd

In [2]:
csv = pd.read_csv(r"C:\Users\Yaseen\Downloads\imdb-top-1000.csv")

In [3]:
csv

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

Business problem data analylis logic code and answer business interpretation  
1] Company ko kya chahiye  
2] Data analysis logic  
Kaunse column aur pandas aperations  
3] code and answer  
result display  
4] Business interpreation:- Result -> basis -->  decision  data limitataion

In [4]:
# 1 Audience Engagement
# Which Movies have the strongest audince engaegement singal in the
csv.nlargest(10, "No_of_Votes")[["Series_Title", "Genre","IMDB_Rating","No_of_Votes"]]

,Series_Title,Genre,IMDB_Rating,No_of_Votes
0,The Shawshank Redemption,Drama,9.3,2343110
2,The Dark Knight,Action,9.0,2303232
8,Inception,Action,8.8,2067042
9,Fight Club,Drama,8.8,1854740
6,Pulp Fiction,Crime,8.9,1826188
11,Forrest Gump,Drama,8.8,1809221
14,The Matrix,Action,8.7,1676426
10,The Lord of the Rings: The Fellowship of the Ring,Action,8.8,1661481
5,The Lord of the Rings: The Return of the King,Action,8.9,1642758
1,The Godfather,Crime,9.2,1620367

In [5]:
# problem -2 Hight Quality Movies Shortlist
# find movies with rating at least 8.and at least 100,000
shortlist = csv[(csv["IMDB_Rating"] >= 8.5) & (csv["No_of_Votes"] >= 100000)] 
shortlist[["Series_Title", "Genre", "IMDB_Rating", "No_of_Votes" ]]

,Series_Title,Genre,IMDB_Rating,No_of_Votes
0,The Shawshank Redemption,Drama,9.3,2343110
1,The Godfather,Crime,9.2,1620367
2,The Dark Knight,Action,9.0,2303232
3,The Godfather: Part II,Crime,9.0,1129952
4,12 Angry Men,Crime,9.0,689845
5,The Lord of the Rings: The Return of the King,Action,8.9,1642758
6,Pulp Fiction,Crime,8.9,1826188
7,Schindler's List,Biography,8.9,1213505
8,Inception,Action,8.8,2067042
9,Fight Club,Drama,8.8,1854740
10,The Lord of the Rings: The Fellowship of the Ring,Action,8.8,1661481
11,Forrest Gump,Drama,8.8,1809221
12,"Il buono, il brutto, il cattivo",Western,8.8,688390
13,The Lord of the Rings: The Two Towers,Action,8.7,1485555
14,The Matrix,Action,8.7,1676426
15,Goodfellas,Biography,8.7,1020727
16,Star Wars: Episode V - The Empire Strikes Back,Action,8.7,1159315
17,One Flew Over the Cuckoo's Nest,Drama,8.7,918088
19,Gisaengchung,Comedy,8.6,552778
21,Interstellar,Adventure,8.6,1512360
22,Cidade de Deus,Crime,8.6,699256
23,Sen to Chihiro no kamikakushi,Animation,8.6,651376
24,Saving Private Ryan,Drama,8.6,1235804
25,The Green Mile,Crime,8.6,1147794
26,La vita è bella,Comedy,8.6,623629
27,Se7en,Crime,8.6,1445096
28,The Silence of the Lambs,Crime,8.6,1270197
29,Star Wars,Action,8.6,1231473
31,Shichinin no samurai,Action,8.6,315744
32,It's a Wonderful Life,Drama,8.6,405801
33,Joker,Crime,8.5,939252
34,Whiplash,Drama,8.5,717585
35,The Intouchables,Biography,8.5,760360
36,The Prestige,Drama,8.5,1190259
37,The Departed,Crime,8.5,1189773
38,The Pianist,Biography,8.5,729603
39,Gladiator,Action,8.5,1341460
40,American History X,Drama,8.5,1034705
41,The Usual Suspects,Crime,8.5,991208
42,Léon,Action,8.5,1035236
43,The Lion King,Animation,8.5,942045
44,Terminator 2: Judgment Day,Action,8.5,995506
45,Nuovo Cinema Paradiso,Drama,8.5,230763
46,Hotaru no haka,Animation,8.5,235231
47,Back to the Future,Adventure,8.5,1058081
48,Once Upon a Time in the West,Western,8.5,302844
49,Psycho,Horror,8.5,604211
50,Casablanca,Drama,8.5,522093
51,Modern Times,Comedy,8.5,217881
52,City Lights,Comedy,8.5,167839

In [6]:
# Problem 3
# genre performane report
# which genre have hight rating longer runtime and more audice vote
# log, groupby, agg, max, mean, sum
genre_report = csv.groupby("Genre").agg(
    Movie_Count=("Series_Title", "count"),
    Average_Rating=("IMDB_Rating", "mean"),
    Median_Rating=("IMDB_Rating", "median"),
    Average_Runtime=("Runtime", "mean"),
    Total_Votes=("No_of_Votes", "sum")
)

genre_report.sort_values(
    "Average_Rating", ascending=False
)

,Movie_Count,Average_Rating,Median_Rating,Average_Runtime,Total_Votes
Genre,,,,,
Western,4,8.350000,8.4,148.250000,1289665
Crime,107,8.016822,8.0,126.392523,33533615
Fantasy,2,8.000000,8.0,85.000000,146222
Mystery,12,7.975000,8.0,119.083333,4203004
Film-Noir,3,7.966667,8.0,104.000000,367215
Drama,289,7.957439,8.0,124.737024,61367304
Action,172,7.949419,7.9,129.046512,72282412
Biography,88,7.938636,7.9,136.022727,24006844
Adventure,72,7.937500,7.9,134.111111,22576163
Animation,82,7.930488,7.9,99.585366,21978630
Horror,11,7.909091,7.8,102.090909,3742556
Comedy,155,7.901290,7.9,112.129032,27620327
Family,2,7.800000,7.8,107.500000,551221
Thriller,1,7.800000,7.8,108.000000,27733

In [7]:


# Find the top 10 highest-rated movies.

In [8]:
# Which movie has the highest number of votes?
highest=csv.nlargest(5, "No_of_Votes")[["Series_Title","Genre","No_of_Votes",]]
highest

               Series_Title   Genre  No_of_Votes
0  The Shawshank Redemption   Drama      2343110
2           The Dark Knight  Action      2303232
8                 Inception  Action      2067042
9                Fight Club   Drama      1854740
6              Pulp Fiction   Crime      1826188

In [9]:
# Which movies have rating > 8.5?
H_Rating=csv.loc[csv["IMDB_Rating"] > 8.5, ["Series_Title","Genre","IMDB_Rating"]]
H_Rating

                                         Series_Title      Genre  IMDB_Rating
0                            The Shawshank Redemption      Drama          9.3
1                                       The Godfather      Crime          9.2
2                                     The Dark Knight     Action          9.0
3                              The Godfather: Part II      Crime          9.0
4                                        12 Angry Men      Crime          9.0
5       The Lord of the Rings: The Return of the King     Action          8.9
6                                        Pulp Fiction      Crime          8.9
7                                    Schindler's List  Biography          8.9
8                                           Inception     Action          8.8
9                                          Fight Club      Drama          8.8
10  The Lord of the Rings: The Fellowship of the Ring     Action          8.8
11                                       Forrest Gump      Drama          8.8
12                    Il buono, il brutto, il cattivo    Western          8.8
13              The Lord of the Rings: The Two Towers     Action          8.7
14                                         The Matrix     Action          8.7
15                                         Goodfellas  Biography          8.7
16     Star Wars: Episode V - The Empire Strikes Back     Action          8.7
17                    One Flew Over the Cuckoo's Nest      Drama          8.7
18                                           Hamilton  Biography          8.6
19                                       Gisaengchung     Comedy          8.6
20                                    Soorarai Pottru      Drama          8.6
21                                       Interstellar  Adventure          8.6
22                                     Cidade de Deus      Crime          8.6
23                      Sen to Chihiro no kamikakushi  Animation          8.6
24                                Saving Private Ryan      Drama          8.6
25                                     The Green Mile      Crime          8.6
26                                    La vita è bella     Comedy          8.6
27                                              Se7en      Crime          8.6
28                           The Silence of the Lambs      Crime          8.6
29                                          Star Wars     Action          8.6
30                                            Seppuku     Action          8.6
31                               Shichinin no samurai     Action          8.6
32                              It's a Wonderful Life      Drama          8.6

In [11]:
# Genre-wise average rating and average runtime?
Average=csv.groupby("Genre").agg(Avg_Rating=("IMDB_Rating", "mean"), Avg_Runtime=("Runtime","mean"))
Average

           Avg_Rating  Avg_Runtime
Genre
Action       7.949419   129.046512
Adventure    7.937500   134.111111
Animation    7.930488    99.585366
Biography    7.938636   136.022727
Comedy       7.901290   112.129032
Crime        8.016822   126.392523
Drama        7.957439   124.737024
Family       7.800000   107.500000
Fantasy      8.000000    85.000000
Film-Noir    7.966667   104.000000
Horror       7.909091   102.090909
Mystery      7.975000   119.083333
Thriller     7.800000   108.000000
Western      8.350000   148.250000

In [14]:
csv.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [18]:
print(csv.shape)

(1000, 10)